execute_process(COMMAND git apply --reverse --check ${PATCH} RESULT_VARIABLE applied OUTPUT_QUIET ERROR_QUIET)
if(applied EQUAL 0)
    return()
endif()
execute_process(COMMAND git checkout -- . RESULT_VARIABLE reset)
execute_process(COMMAND git apply ${PATCH} RESULT_VARIABLE result)
if(NOT reset EQUAL 0 OR NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot apply ${PATCH}")
endif()
